dist: trusty
language: python
python: "3.6"
matrix:
  include:
    - env: SCRIPT=TEST
    - env: SCRIPT=LINT
before_install:
  - pip install pylint
script:
  - if [ "$SCRIPT" = "TEST" ]; then python tests.py; fi
  - if [ "$SCRIPT" = "LINT" ]; then pylint *.py; fi
